# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 18, 51, 11, 204509), verbose_name='date bought'),
            preserve_default=False,
        ),
    ]
