# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_bought_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Wine')),
            ],
        ),
    ]
